### ISSUE TITLE
今天的日期不能被选中

### ISSUE THREAD

**Issue by liuminisaboy** [dse12345z/GTLCalendar#1]
1，设置minimumDateForGTLCalendar为[NSDate new]，那么今天的日子不能被选中
2，比如设置maximumDateForGTLCalendar为@"2017-12-01"，日历显示到2017年11月1日之前才能可选 1日-30日都不能被选择。
3，星期怎么设置成这种样式：日 一 二 三 四 五 六

**Comment by dse12345z** [comment]
非常謝謝你~ OvO

問題1、問題2 已經修正
問題3 我沒有做樣式的切換

你想到的話可以修改
1.GTLCalendarView.m
- (NSArray *)itemStringDays {
    return @[@"日", @"一", @"二", @"三", @"四", @"五", @"六"];
}

2.NSCalendar+GTLCategory.m
+ (NSInteger)weekFromMonthFirstDate:(NSDate *)fromDate
NSArray *weeks = @[@0, @0, @1, @2, @3, @4, @5, @6];

如果需要的話我可以修改成一個分支給你

**Comment by dse12345z** [comment]
非常謝謝你~ OvO

問題1、問題2 已經修正
問題3 我沒有做樣式的切換

你想到的話可以修改
1.GTLCalendarView.m

   - (NSArray *)itemStringDays {
   return @[@"日", @"一", @"二", @"三", @"四", @"五", @"六"];
   }

2.NSCalendar+GTLCategory.m

   - (NSInteger)weekFromMonthFirstDate:(NSDate *)fromDate
   NSArray *weeks = @[@0 <https://github.com/0>, @0 <https://github.com/0>,
   @1 <https://github.com/1>, @2 <https://github.com/2>, @3
   <https://github.com/3>, @4 <https://github.com/4>, @5
   <https://github.com/5>, @6 <https://github.com/6>];

如果需要的話我可以修改成一個分支給你

2017-08-31 16:52 GMT+08:00 Sen <notifications@github.com>:

**Comment by dse12345z** [comment]
這個我在想想怎麼加入 GTLCalendar 裡面來切換兩種格式

謝謝你的意見~

**Comment by liuminisaboy** [comment]
分支不用了，感谢你的分享！

**Comment by liuminisaboy** [comment]
选择起止时间的动画能去掉吗？我没有找到在去掉的位置

**Comment by dse12345z** [comment]
不要動畫嗎?


GTLCalendarView.m 
\- (void)recordGradientInfo:(NSDate *)date frame:(CGRect)frame

animateWithDuration:animations: 刪除掉試試
```
437        if (CGRectGetWidth(cacheFrame) < CGRectGetWidth(convertFrame)) {
438            [UIView animateWithDuration:0.5 animations: ^{
439                gtlGradientView.frame = convertFrame;
440            }];
441        }
```
